OlimpiColombia/urls.py
from django.conf.urls import include, url
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from .router import urlpatterns

urlpatterns = [
    url(r'', include('OlimpiColombiaSite.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^usuarios/', include('Usuarios.urls')),
    url('', include('django.contrib.auth.urls', namespace='auth')),
    url('', include('social.apps.django_app.urls', namespace='social')),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^api/', include(urlpatterns)),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

OlimpiColombiaSite/urls.py
from django.conf.urls import url, include
from django.contrib.auth.views import login, logout_then_login, logout
from django.contrib.auth.decorators import login_required

from . import views

app_name = 'OlimpiColombiaSite'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^partials/deportes$', views.IndexView2.as_view(), name="list"),
    url(r'^partials/atletas$', views.IndexView3.as_view(), name="list"),
    url(r'^atletas/(?P<atleta_id>[0-9]+)/$', views.AtletasView.as_view(), name='atleta'),
    url(r'^highlights/(?P<pk>[0-9]+)/$', login_required(views.HighlightView.as_view()), name='highlights'),
    url(r'^calendario/(?P<pk>\d+)/$', login_required(views.CalendarioView.as_view())),
    url(r'^accounts/login/', login, {'template_name': 'login.html'}, name='login'),
    url(r'^logout/', logout_then_login, name='logout'),
    #url(r'^logout/$', logout, {'next_page': '/'}, name='logout'),

]

Usuarios/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^registrar', views.RegistroUsuario.as_view(), name="registrar")
]

OlimpiColombiaSite/models.py
from __future__ import unicode_literals

from django.db import models


# Create your models here.
class Imagen(models.Model):
    url = models.CharField(max_length=1000)


class Deporte(models.Model):
    """
    Describe un deporte.
    """
    nombre = models.CharField(max_length=200)
    descripcion = models.CharField(max_length=1000, blank=True, verbose_name='Descripción')
    imagen = models.CharField(max_length=1000, verbose_name='Imágen', help_text='URL de la imagen del deporte')

    def __str__(self):
        return self.nombre


class Entrenador(models.Model):
    """
    Describe a un Entrenador.
    """
    nombres = models.CharField(max_length=200)

    def __str__(self):
        return self.nombres

    class Meta:
        verbose_name_plural = 'Entrenadores'


class Atleta(models.Model):
    """
    Describe a un Atleta.
    """
    nombres = models.CharField(max_length=200)
    lugar_nacimiento = models.CharField(max_length=100)
    fecha_nacimiento = models.DateField()
    edad = models.IntegerField()
    peso = models.DecimalField(max_digits=4, decimal_places=1, help_text='Peso en kilogramos (kg)')
    estatura = models.DecimalField(max_digits=4, decimal_places=1, help_text='Estatura en centimetros (cm)')
    fotografia = models.CharField(max_length=1000, verbose_name='Fotografía', help_text='URL de la imagen del atleta')
    deporte = models.ForeignKey(Deporte, on_delete=models.CASCADE)
    entrenador = models.ForeignKey(Entrenador, on_delete=models.CASCADE, null=True)
    video_destacado = models.FileField(null=True)

    def __str__(self):
        return self.nombres


class Modalidad(models.Model):
    """
    Defina la modalidad de un deporte
    """
    nombre = models.CharField(max_length=70)
    deporte = models.ForeignKey(Deporte, on_delete=models.CASCADE)

    def __str__(self):
        return '%s, %s' % (self.nombre, self.deporte.nombre)

    class Meta:
        verbose_name_plural = 'Modalidades'


class Competencia(models.Model):
    """
    Describe una competencia para un deporte.
    """
    fecha = models.DateTimeField()
    descripcion = models.CharField(max_length=200, blank=True, verbose_name='Descripción')
    modalidad = models.ForeignKey(Modalidad, on_delete=models.CASCADE)

    def __str__(self):
        return self.descripcion


class Resultado(models.Model):
    competencia = models.ForeignKey(Competencia, on_delete=models.CASCADE)
    atleta = models.ForeignKey(Atleta, on_delete=models.CASCADE)
    resultado = models.CharField(max_length=100, blank=True)

    def __str__(self):
        return self.resultado

class Highlight(models.Model):
    """
    Modelo para guardar los highlights de las competencias incluyendo el atleta resaltado.
    """
    atleta = models.ForeignKey(Atleta)
    competencia = models.OneToOneField(Resultado, related_name='momento_destacado')
    video = models.FileField()

Usuarios/models.py
from django.db import models

# Create your models here.

Usuarios/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class RegistroForm(UserCreationForm):
    class Meta:
        model = User
        fields = [
            'username',
            'first_name',
            'last_name',
            'email',
        ]
        labels = {
            'username': 'Nombre de Usuario Uniandes',
            'first_name': 'Nombre',
            'last_name': 'Apellido',
            'email': 'Correo electrónico',
        }

OlimpiColombiaSite/views.py
from django.shortcuts import get_object_or_404
from django.views.generic import *
from .models import *


class IndexView(ListView):
    template_name = 'OlimpiColombiaSite/index.html'
    context_object_name = 'lista_deportes'
    queryset = Deporte.objects.all()
    #serializer_class = DeporteSerializer

    def get_queryset(self):
        return Deporte.objects.all()


class IndexView2(ListView):
    template_name = 'OlimpiColombiaSite/partials/deportes.html'
    context_object_name = 'lista_deportes'
    queryset = Deporte.objects.all()

class IndexView3(ListView):
    template_name = 'OlimpiColombiaSite/partials/atletas.html'
    context_object_name = 'lista_deportes'
    queryset = Deporte.objects.all()



class AtletasView(ListView):
    template_name = 'OlimpiColombiaSite/atletas.html'
    context_object_name = 'lista_atletas'
    deporte = Deporte

    def get_queryset(self):
        self.deporte = get_object_or_404(Deporte, id=int(self.kwargs['atleta_id']))
        return Atleta.objects.filter(deporte__pk=self.deporte.pk)

    def get_context_data(self, **kwargs):
        context = super(AtletasView, self).get_context_data(**kwargs)
        context['deporte'] = self.deporte
        return context


class CalendarioView(ListView):
    template_name = 'OlimpiColombiaSite/calendario.html'
    atleta = Atleta
    modalidad = Modalidad
    competencia = Competencia
    resultado = Resultado

    def get_queryset(self):
        self.atleta = get_object_or_404(Atleta, id=int(self.kwargs['pk']))
        self.resultado = Resultado.objects.filter(atleta__pk=self.atleta.pk)
        return self.resultado

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super(CalendarioView, self).get_context_data(**kwargs)
        # Add in the publisher

        context['atleta'] = self.atleta

        return context

class HighlightView(DetailView):
    template_name = 'OlimpiColombiaSite/highlight.html'
    model = Highlight

Usuarios/views.py
from django.contrib.auth.models import User
from django.views.generic import CreateView
from django.core.urlresolvers import reverse_lazy
from Usuarios.forms import RegistroForm
# Create your views here.


class RegistroUsuario(CreateView):
    model = User
    template_name = "usuarios/registrar.html"
    form_class = RegistroForm
    success_url = reverse_lazy('OlimpiColombiaSite:login')

OlimpiColombiaSite/templates/OlimpiColombiaSite/atletas.html
{% load static %}
{# load the tag library #}
{% load bootstrap3 %}

{# load css and javascript #}
{% bootstrap_css %}
{% bootstrap_javascript %}
<link rel="stylesheet" type="text/css" href="{% static 'OlimpiColombiaSite/stylesheets/main.css' %}" />

    <script src="{% static 'OlimpiColombiaSite/scripts/angular-1.5.8.js' %}"></script>
    <script src="{% static 'OlimpiColombiaSite/scripts/angular-route-1.5.8.js' %}"></script>
    <script src="{% static 'OlimpiColombiaSite/scripts/controllers.js' %}"></script>


<nav class="navbar navbar-default" role="navigation">
  <!-- El logotipo y el icono que despliega el menú se agrupan
       para mostrarlos mejor en los dispositivos móviles -->
  <div class="navbar-header">
    <a class="navbar-brand" href="{% url 'OlimpiColombiaSite:index' %}">OlimpiColombia</a>
  </div>

  <!-- Agrupar los enlaces de navegación, los formularios y cualquier
       otro elemento que se pueda ocultar al minimizar la barra -->
  <div class="collapse navbar-collapse navbar-ex1-collapse">
    <ul class="nav navbar-nav navbar-right">
        {% if user.is_authenticated %}
            <li><a href="#">Bienvenid@, {{ user.get_username }}.</a></li>
            <li><a href="/logout/">Salir</a></li>
        {% else %}
            <li><a href="/accounts/login/">Login</a></li>
            <li><a href="/usuarios/registrar">Registro</a></li>
        {% endif %}

    </ul>
  </div>
</nav>

<div class="panel panel-primary">
<h1 align="center">{{ deporte.nombre }}</h1>
</div>

{% for atleta in lista_atletas %}
    {% if forloop.first %}<div class="row">{% endif %}
    <div class="col-sm-6 col-md-4">
        <div class="thumbnail">
            <a href="#" >
                <img class="img-responsive img-rounded" src="{{ atleta.fotografia }}" width="150" height="178"/>
            </a>
            <div class="caption">
               <table class="table table-striped">
                    <tr>
                        <th>Nombre</th>
                        <td>{{ atleta.nombres }}</td>
                    </tr>
                    <tr>
                        <th>Fecha nacimiento</th>
                        <td>{{ atleta.fecha_nacimiento }}</td>
                    </tr>
                    <tr>
                        <th>Edad</th>
                        <td>{{ atleta.edad }}</td>
                    </tr>
                    <tr>
                        <th>Peso</th>
                        <td>{{ atleta.peso }}</td>
                    </tr>
                    <tr>
                        <th>Estatura</th>
                        <td>{{ atleta.estatura }}</td>
                    </tr>
                    <tr>
                        <td><a href="/calendario/{{ atleta.id }}" >Resultados Competencia</a></td>
                    </tr>
               </table>
            </div>
        </div>
    </div>
    {% if forloop.counter|divisibleby:3 %}</div><div class="row">{% endif %}
    {% if forloop.last %}</div>{% endif %}
{% endfor %}

OlimpiColombiaSite/templates/OlimpiColombiaSite/calendario.html
{% load static %}
{# load the tag library #}
{% load bootstrap3 %}

{# load css and javascript #}
{% bootstrap_css %}
{% bootstrap_javascript %}
<link rel="stylesheet" type="text/css" href="{% static 'OlimpiColombiaSite/stylesheets/main.css' %}" />

<nav class="navbar navbar-default" role="navigation">
  <!-- El logotipo y el icono que despliega el menú se agrupan
       para mostrarlos mejor en los dispositivos móviles -->
  <div class="navbar-header">
    <a class="navbar-brand" href="{% url 'OlimpiColombiaSite:index' %}">OlimpiColombia</a>
  </div>

  <!-- Agrupar los enlaces de navegación, los formularios y cualquier
       otro elemento que se pueda ocultar al minimizar la barra -->
  <div class="collapse navbar-collapse navbar-ex1-collapse">
    <ul class="nav navbar-nav navbar-right">
        {% if user.is_authenticated %}
            <li><a href="#">Bienvenid@, {{ user.get_username }}.</a></li>
            <li><a href="/logout/">Salir</a></li>
        {% else %}
            <li><a href="/accounts/login/">Login</a></li>
            <li><a href="/usuarios/registrar">Registro</a></li>
        {% endif %}

    </ul>
  </div>
</nav>
<div class="panel panel-primary">
<h1 align="center">Calendario</h1>
</div>


<div class="row">
    <div class="col-sm-6 col-md-1" >
        <div class="thumbnail">
            <img class="img-responsive img-rounded" src="{{ atleta.fotografia }}" width="50" height="70"/>
        </div>
    </div>
    <div class="col-sm-6 col-md-4">
        <div class="thumbnail">
            <h3 align="center"> {{ atleta.nombres }} </h3>
        </div>
    </div>
    <div class="col-sm-6 col-md-1">
        <div class="thumbnail">
            <img class="img-responsive img-rounded" src="{{ atleta.deporte.imagen }}" width="50" height="70"/>
        </div>
    </div>
    <div class="col-sm-6 col-md-4">
        <div class="thumbnail">
        <h3 align="center">{{ atleta.deporte.nombre }}</h3>
        </div>
    </div>
</div>

{% for resultado in object_list %}
    <div>
        <div class="panel panel-info">
            <h3 align="center">{{  resultado.competencia.modalidad.nombre }}</h3>
        </div>

        <div class="container">
        <table class="table table-striped">
            <thead>
                <tr>
                    <td><b>Fecha de Competencia</b></td>
                    <td><b>Descripción de la competencia</b></td>
                    <td><b>Resultado</b></td>
                </tr>
                <tr>
                    <td>{{ resultado.competencia.fecha }}</td>
                    <td>{{ resultado.competencia.descripcion }}</td>
                    <td>{{ resultado.resultado }}</td>
                </tr>
            </thead>
        </table>
        {% if resultado.momento_destacado %} <a href="/highlights/{{resultado.momento_destacado.id}}">Momento Destacado</a> {%endif%}
        </div>
    </div>
    {% empty %}
        <center><b>Lo sentimos, Actualmente no hay eventos registrados para este atleta</b></center>
{% endfor %}

OlimpiColombiaSite/templates/OlimpiColombiaSite/deportes.html
<html ng-app="OlimpiColombiaApp">
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/es_LA/sdk.js#xfbml=1&version=v2.7&appId=1751071491798946";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

{% load static %}
{# load the tag library #}
{% load bootstrap3 %}

{# load css and javascript #}
{% bootstrap_css %}
{% bootstrap_javascript %}
<link rel="stylesheet" type="text/css" href="{% static 'OlimpiColombiaSite/stylesheets/main.css' %}" />
<script src="{% static 'OlimpiColombiaSite/scripts/angular-1.5.8.js' %}"></script>
<script src="{% static 'OlimpiColombiaSite/scripts/angular-route-1.5.8.js' %}"></script>
<script src="https://code.angularjs.org/1.5.8/angular-resource.min.js"></script>
<script src="{% static 'OlimpiColombiaSite/scripts/app.js' %}"></script>
<script src="{% static 'OlimpiColombiaSite/scripts/controllers.js' %}"></script>


<nav class="navbar navbar-default" role="navigation">
  <!-- El logotipo y el icono que despliega el menú se agrupan
       para mostrarlos mejor en los dispositivos móviles -->
  <div class="navbar-header">
    <a class="navbar-brand" href="{% url 'OlimpiColombiaSite:index' %}">OlimpiColombia</a>
  </div>

  <!-- Agrupar los enlaces de navegación, los formularios y cualquier
       otro elemento que se pueda ocultar al minimizar la barra -->
  <div class="collapse navbar-collapse navbar-ex1-collapse">
    <ul class="nav navbar-nav navbar-right">
        {% if user.is_authenticated %}
            <li><a href="#">Bienvenid@, {{ user.get_username }}.</a></li>
            <li><a  href="/logout/">Salir</a></li>

        {% else %}
            <li><a href="/accounts/login/">Login</a></li>
            <li><a href="/usuarios/registrar">Registro</a></li>
        {% endif %}
    </ul>
  </div>
</nav>



<div class="panel panel-primary" >
<h1 align="center">OlimpiColombia</h1>
</div>

{% verbatim %}
<div ng-app="OlimpiColombiaApp"  ng-controller="DeporteController">
<div class="row">
    <div ng-repeat="deporte in deportes">
        <div class="clearfix" ng-if="$index % 3 == 0"></div>
        <div class="col-sm-6 col-md-4">
            <div class="thumbnail">
                <a href="/atletas/{{deporte.id}}" >
                    <img class="img-responsive img-rounded" src="{{ deporte.imagen }}" width="150" height="178"/>
                </a>
                <div class="caption">
                    <h3>{{ deporte.nombre }}</h3>
                    <p>{{ deporte.descripcion }}</p>
                </div>
            </div>
        </div>
    </div>
</div>
</div>
{% endverbatim %}
</html>

OlimpiColombiaSite/templates/OlimpiColombiaSite/highlight.html
{% load static %}
{# load the tag library #}
{% load bootstrap3 %}

{# load css and javascript #}
{% bootstrap_css %}
{% bootstrap_javascript %}
<link rel="stylesheet" type="text/css" href="{% static 'OlimpiColombiaSite/stylesheets/main.css' %}" />

<nav class="navbar navbar-default" role="navigation">
  <!-- El logotipo y el icono que despliega el menú se agrupan
       para mostrarlos mejor en los dispositivos móviles -->
  <div class="navbar-header">
    <a class="navbar-brand" href="{% url 'OlimpiColombiaSite:index' %}">OlimpiColombia</a>
  </div>

  <!-- Agrupar los enlaces de navegación, los formularios y cualquier
       otro elemento que se pueda ocultar al minimizar la barra -->
  <div class="collapse navbar-collapse navbar-ex1-collapse">
    <ul class="nav navbar-nav navbar-right">
        {% if user.is_authenticated %}
            <li><a href="#">Bienvenid@, {{ user.get_username }}.</a></li>
            <li><a href="/logout/">Salir</a></li>
        {% else %}
            <li><a href="/accounts/login/">Login</a></li>
            <li><a href="/usuarios/registrar">Registro</a></li>
        {% endif %}

    </ul>
  </div>
</nav>

<center>
  <video width="640" height="480" controls>
    <source src="{{object.video.url}}" type="video/mp4">
    <source src="{{object.video.url}}" type="video/ogg">
    Tu navegador no soporta videos embebidos.
  </video>
  <span class='st_facebook_vcount' displayText='Facebook'></span>
  <span class='st_twitter_vcount' displayText='Tweet'></span>
  <script type="text/javascript" src="https://ws.sharethis.com/button/buttons.js"></script>
<script type="text/javascript">stLight.options({publisher: "0116aee8-382b-4f40-a739-ac6f0bf99730", doNotHash: true, doNotCopy: false, hashAddressBar: false});</script>
</center>

OlimpiColombiaSite/templates/OlimpiColombiaSite/index.html
<!doctype html>
<html ng-app="OlimpiColombiaApp">
<head>
    <script>(function(d, s, id) {
      var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = "//connect.facebook.net/es_LA/sdk.js#xfbml=1&version=v2.7&appId=1751071491798946";
    fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));</script>

    {% load static %}
    {# load the tag library #}
    {% load bootstrap3 %}

    {# load css and javascript #}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
	<title>OlimpiColombia</title>
	<link rel="stylesheet" type="text/css" href="{% static 'OlimpiColombiaSite/stylesheets/main.css' %}" />
    <script src="{% static 'OlimpiColombiaSite/scripts/angular-1.5.8.js' %}"></script>
    <script src="{% static 'OlimpiColombiaSite/scripts/angular-route-1.5.8.js' %}"></script>
    <script src="https://code.angularjs.org/1.5.8/angular-resource.min.js"></script>
    <script src="{% static 'OlimpiColombiaSite/scripts/app.js' %}"></script>
    <script src="{% static 'OlimpiColombiaSite/scripts/controllers.js' %}"></script>

</head>
<body>


<nav class="navbar navbar-default" role="navigation">
  <!-- El logotipo y el icono que despliega el menú se agrupan
       para mostrarlos mejor en los dispositivos móviles -->
  <div class="navbar-header">
    <a class="navbar-brand" href="{% url 'OlimpiColombiaSite:index' %}">OlimpiColombia</a>
  </div>

  <!-- Agrupar los enlaces de navegación, los formularios y cualquier
       otro elemento que se pueda ocultar al minimizar la barra -->
  <div class="collapse navbar-collapse navbar-ex1-collapse">
    <ul class="nav navbar-nav navbar-right">
        {% if user.is_authenticated %}
            <li><a href="#">Bienvenid@, {{ user.get_username }}.</a></li>
            <li><a  href="/logout/">Salir</a></li>

        {% else %}
            <li><a href="/accounts/login/">Login</a></li>
            <li><a href="/usuarios/registrar">Registro</a></li>
        {% endif %}
    </ul>
  </div>
</nav>





<div class="main" ng-view>

	 <!-- everthing here was gone to list.html file inside partials folder -->

</div>
</body>
</html>

OlimpiColombiaSite/templates/OlimpiColombiaSite/partials/deportes.html
{% verbatim %}

<div class="panel panel-primary" >
<h1 align="center">OlimpiColombia</h1>
</div>




<div class="row">
    <div ng-repeat="deporte in deportes">
        <div class="clearfix" ng-if="$index % 3 == 0"></div>
        <div class="col-sm-6 col-md-4">
            <div class="thumbnail">
                <a href="#/atletas/{{deporte.id}}" >
                    <img class="img-responsive img-rounded" src="{{ deporte.imagen }}" width="150" height="178"/>
                </a>
                <div class="caption">
                    <h3>{{ deporte.nombre }}</h3>
                    <p>{{ deporte.descripcion }}</p>
                </div>
            </div>
        </div>
    </div>
</div>
{% endverbatim %}

templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/es_LA/sdk.js#xfbml=1&version=v2.7&appId=1751071491798946";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
{% load static %}
{# load the tag library #}
{% load bootstrap3 %}

{# load css and javascript #}
{% bootstrap_css %}
{% bootstrap_javascript %}
<nav class="navbar navbar-default" role="navigation">
  <!-- El logotipo y el icono que despliega el menú se agrupan
       para mostrarlos mejor en los dispositivos móviles -->
  <div class="navbar-header">
    <a class="navbar-brand" href="{% url 'OlimpiColombiaSite:index' %}">OlimpiColombia</a>
  </div>

  <!-- Agrupar los enlaces de navegación, los formularios y cualquier
       otro elemento que se pueda ocultar al minimizar la barra -->
  <div class="collapse navbar-collapse navbar-ex1-collapse">
    <ul class="nav navbar-nav navbar-right">
      <li><a href="/usuarios/registrar">Registro</a></li>
    </ul>
  </div>
</nav>

<form method="post">
    {% csrf_token %}


    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="form-group">
                <label>Nombre de usuario uniandes</label>
                <input class="form-control" type="text" name="username"/>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="form-group">
                <label>Contraseña</label>
                <input class="form-control" type="password" name="password"/>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="form-group">
                <a href="#">Olvide mi contraseña</a>
                 <button class="btn btn-primary" type="submit">Ingresar</button>
            </div>
            <div class="form-group">
                {% if not user.is_authenticated %}
                    <div class="fb-login-button" data-max-rows="1" data-size="large" data-show-faces="false" data-auto-logout-link="false" onlogin="window.location.href='{% url 'social:begin' 'facebook' %}?next=/'" scope="email"></div>
                {% endif %}

            </div>
        </div>
    </div>
</form>
</body>
</html>

templates/usuarios/registrar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% load static %}
{# load the tag library #}
{% load bootstrap3 %}

{# load css and javascript #}
{% bootstrap_css %}
{% bootstrap_javascript %}
<nav class="navbar navbar-default" role="navigation">
  <!-- El logotipo y el icono que despliega el menú se agrupan
       para mostrarlos mejor en los dispositivos móviles -->
  <div class="navbar-header">
    <a class="navbar-brand" href="{% url 'OlimpiColombiaSite:index' %}">OlimpiColombia</a>
  </div>

  <!-- Agrupar los enlaces de navegación, los formularios y cualquier
       otro elemento que se pueda ocultar al minimizar la barra -->
  <div class="collapse navbar-collapse navbar-ex1-collapse">
    <ul class="nav navbar-nav navbar-right">
      <li><a href="/accounts/login/">Login</a></li>
    </ul>
  </div>
</nav>

<form method="post">
    {% csrf_token %}

    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="form-group">
                <label>Nombre</label>
                <input class="form-control" type="text" name="first_name"/>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="form-group">
                <label>Apellidos</label>
                <input class="form-control" type="text" name="last_name"/>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="form-group">
                <label>Nombre de usuario uniandes</label>
                <input class="form-control" type="text" name="username"/>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="form-group">
                <label>Correo electrónico</label>
                <input class="form-control" type="text" name="email"/>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="form-group">
                <label>Contraseña</label>
                <input class="form-control" type="password" name="password1"/>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="form-group">
                <label>Confirmar contraseña</label>
                <input class="form-control" type="password" name="password2"/>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="form-group">
                 <button class="btn btn-primary" type="submit">Guardar</button>
            </div>
        </div>
    </div>

</form>
</body>
</html>